---
abstract: 'PSGI Log handler for Dancer'
author:
  - 'franck cuny <franck@lumberjaph.net>'
build_requires:
  Dancer: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Plack::Builder: 0
  Plack::Loader: 0
  Test::More: 0
  Test::Requires: 0
  Test::TCP: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Logger-PSGI
requires:
  Dancer::Logger::Abstract: 0
  Dancer::SharedData: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/franckcuny/dancer-logger-psgi/issues
  homepage: https://metacpan.org/release/Dancer-Logger-PSGI
  repository: git://github.com/franckcuny/dancer-logger-psgi.git
version: 0.020_001
